// DONT CHANGE THIS FILE!
// This file is used to help the tutors try to understand your configuration better

#include "ArchVMXDefinitions.h"
#include "kprintf.h"
#include "debug.h"
#include "Mutex.h"
#include "ScopeLock.h"
#include "umap.h"
#include "ustring.h"


static Mutex vmprintlock("vmprintlock");
static ustl::map<size_t, ustl::string> print_map;
void setupGuestPrinting() {
  new (&vmprintlock) Mutex("vmprintlock");
  new (&print_map) ustl::map<size_t, ustl::string>;
}
// Print all guest debug output line buffered with this function
void printGuestDebug(char ch, size_t id) {
  ScopeLock lock(vmprintlock);
  ustl::string &str = print_map[id];
  if (str.empty()) {
    str += "[" + ustl::to_string(id) + "]";
  }
  str += ch;
  if (ch == '\n') {
    debug(GUEST, "%s", str.c_str());
    str.clear();
  }
}

#define VMX_DUMP(_x) kprintfd("'" #_x "' : %016lx,\n", vmread(_x))
#define MSR_DUMP(_x) kprintfd("'" #_x "' : %016lx,\n", rdmsr(_x))

void dump_vmx_msrs() {
    kprintfd("msrs = {\n");
    MSR_DUMP(MSR_IA32_FEATURE_CONTROL);
    MSR_DUMP(MSR_FS_BASE);
    MSR_DUMP(MSR_GS_BASE);
    MSR_DUMP(MSR_IA32_SYSENTER_CS);
    MSR_DUMP(MSR_IA32_SYSENTER_ESP);
    MSR_DUMP(MSR_IA32_SYSENTER_EIP);
    MSR_DUMP(MSR_IA32_DEBUGCTL);
    MSR_DUMP(MSR_IA32_VMX_BASIC);
    MSR_DUMP(MSR_IA32_VMX_PINBASED_CTLS);
    MSR_DUMP(MSR_IA32_VMX_PROCBASED_CTLS);
    MSR_DUMP(MSR_IA32_VMX_EXIT_CTLS);
    MSR_DUMP(MSR_IA32_VMX_ENTRY_CTLS);
    MSR_DUMP(MSR_IA32_VMX_MISC);
    MSR_DUMP(MSR_IA32_VMX_CR0_FIXED0);
    MSR_DUMP(MSR_IA32_VMX_CR0_FIXED1);
    MSR_DUMP(MSR_IA32_VMX_CR4_FIXED0);
    MSR_DUMP(MSR_IA32_VMX_CR4_FIXED1);
    MSR_DUMP(MSR_IA32_VMX_VMCS_ENUM);
    MSR_DUMP(MSR_IA32_VMX_PROCBASED_CTLS2);
    MSR_DUMP(MSR_IA32_VMX_EPT_VPID_CAP);
    MSR_DUMP(MSR_IA32_VMX_TRUE_PINBASED_CTLS);
    MSR_DUMP(MSR_IA32_VMX_TRUE_PROCBASED_CTLS);
    MSR_DUMP(MSR_IA32_VMX_TRUE_EXIT_CTLS);
    MSR_DUMP(MSR_IA32_VMX_TRUE_ENTRY_CTLS);
    kprintfd("}\n");
}

void dump_vmx_config() {
    kprintfd("vmx = {\n");
    VMX_DUMP(VIRTUAL_PROCESSOR_ID);
    VMX_DUMP(POSTED_INTR_NV);
    VMX_DUMP(GUEST_ES_SELECTOR);
    VMX_DUMP(GUEST_CS_SELECTOR);
    VMX_DUMP(GUEST_SS_SELECTOR);
    VMX_DUMP(GUEST_DS_SELECTOR);
    VMX_DUMP(GUEST_FS_SELECTOR);
    VMX_DUMP(GUEST_GS_SELECTOR);
    VMX_DUMP(GUEST_LDTR_SELECTOR);
    VMX_DUMP(GUEST_TR_SELECTOR);
    VMX_DUMP(GUEST_INTR_STATUS);
    VMX_DUMP(GUEST_PML_INDEX);
    VMX_DUMP(HOST_ES_SELECTOR);
    VMX_DUMP(HOST_CS_SELECTOR);
    VMX_DUMP(HOST_SS_SELECTOR);
    VMX_DUMP(HOST_DS_SELECTOR);
    VMX_DUMP(HOST_FS_SELECTOR);
    VMX_DUMP(HOST_GS_SELECTOR);
    VMX_DUMP(HOST_TR_SELECTOR);
    VMX_DUMP(IO_BITMAP_A);
    VMX_DUMP(IO_BITMAP_A_HIGH);
    VMX_DUMP(IO_BITMAP_B);
    VMX_DUMP(IO_BITMAP_B_HIGH);
    VMX_DUMP(MSR_BITMAP);
    VMX_DUMP(MSR_BITMAP_HIGH);
    VMX_DUMP(VM_EXIT_MSR_STORE_ADDR);
    VMX_DUMP(VM_EXIT_MSR_STORE_ADDR_HIGH);
    VMX_DUMP(VM_EXIT_MSR_LOAD_ADDR);
    VMX_DUMP(VM_EXIT_MSR_LOAD_ADDR_HIGH);
    VMX_DUMP(VM_ENTRY_MSR_LOAD_ADDR);
    VMX_DUMP(VM_ENTRY_MSR_LOAD_ADDR_HIGH);
    VMX_DUMP(PML_ADDRESS);
    VMX_DUMP(PML_ADDRESS_HIGH);
    VMX_DUMP(TSC_OFFSET);
    VMX_DUMP(TSC_OFFSET_HIGH);
    VMX_DUMP(VIRTUAL_APIC_PAGE_ADDR);
    VMX_DUMP(VIRTUAL_APIC_PAGE_ADDR_HIGH);
    VMX_DUMP(APIC_ACCESS_ADDR);
    VMX_DUMP(APIC_ACCESS_ADDR_HIGH);
    VMX_DUMP(POSTED_INTR_DESC_ADDR);
    VMX_DUMP(POSTED_INTR_DESC_ADDR_HIGH);
    VMX_DUMP(VM_FUNCTION_CONTROL);
    VMX_DUMP(VM_FUNCTION_CONTROL_HIGH);
    VMX_DUMP(EPT_POINTER);
    VMX_DUMP(EPT_POINTER_HIGH);
    VMX_DUMP(EOI_EXIT_BITMAP0);
    VMX_DUMP(EOI_EXIT_BITMAP0_HIGH);
    VMX_DUMP(EOI_EXIT_BITMAP1);
    VMX_DUMP(EOI_EXIT_BITMAP1_HIGH);
    VMX_DUMP(EOI_EXIT_BITMAP2);
    VMX_DUMP(EOI_EXIT_BITMAP2_HIGH);
    VMX_DUMP(EOI_EXIT_BITMAP3);
    VMX_DUMP(EOI_EXIT_BITMAP3_HIGH);
    VMX_DUMP(EPTP_LIST_ADDRESS);
    VMX_DUMP(EPTP_LIST_ADDRESS_HIGH);
    VMX_DUMP(VMREAD_BITMAP);
    VMX_DUMP(VMREAD_BITMAP_HIGH);
    VMX_DUMP(VMWRITE_BITMAP);
    VMX_DUMP(VMWRITE_BITMAP_HIGH);
    VMX_DUMP(XSS_EXIT_BITMAP);
    VMX_DUMP(XSS_EXIT_BITMAP_HIGH);
    VMX_DUMP(ENCLS_EXITING_BITMAP);
    VMX_DUMP(ENCLS_EXITING_BITMAP_HIGH);
    VMX_DUMP(TSC_MULTIPLIER);
    VMX_DUMP(TSC_MULTIPLIER_HIGH);
    VMX_DUMP(GUEST_PHYSICAL_ADDRESS);
    VMX_DUMP(GUEST_PHYSICAL_ADDRESS_HIGH);
    VMX_DUMP(VMCS_LINK_POINTER);
    VMX_DUMP(VMCS_LINK_POINTER_HIGH);
    VMX_DUMP(GUEST_IA32_DEBUGCTL);
    VMX_DUMP(GUEST_IA32_DEBUGCTL_HIGH);
    VMX_DUMP(GUEST_IA32_PAT);
    VMX_DUMP(GUEST_IA32_PAT_HIGH);
    VMX_DUMP(GUEST_IA32_EFER);
    VMX_DUMP(GUEST_IA32_EFER_HIGH);
    VMX_DUMP(GUEST_IA32_PERF_GLOBAL_CTRL);
    VMX_DUMP(GUEST_IA32_PERF_GLOBAL_CTRL_HIGH);
    VMX_DUMP(GUEST_PDPTR0);
    VMX_DUMP(GUEST_PDPTR0_HIGH);
    VMX_DUMP(GUEST_PDPTR1);
    VMX_DUMP(GUEST_PDPTR1_HIGH);
    VMX_DUMP(GUEST_PDPTR2);
    VMX_DUMP(GUEST_PDPTR2_HIGH);
    VMX_DUMP(GUEST_PDPTR3);
    VMX_DUMP(GUEST_PDPTR3_HIGH);
    VMX_DUMP(GUEST_BNDCFGS);
    VMX_DUMP(GUEST_BNDCFGS_HIGH);
    VMX_DUMP(GUEST_IA32_RTIT_CTL);
    VMX_DUMP(GUEST_IA32_RTIT_CTL_HIGH);
    VMX_DUMP(HOST_IA32_PAT);
    VMX_DUMP(HOST_IA32_PAT_HIGH);
    VMX_DUMP(HOST_IA32_EFER);
    VMX_DUMP(HOST_IA32_EFER_HIGH);
    VMX_DUMP(HOST_IA32_PERF_GLOBAL_CTRL);
    VMX_DUMP(HOST_IA32_PERF_GLOBAL_CTRL_HIGH);
    VMX_DUMP(PIN_BASED_VM_EXEC_CONTROL);
    VMX_DUMP(CPU_BASED_VM_EXEC_CONTROL);
    VMX_DUMP(EXCEPTION_BITMAP);
    VMX_DUMP(PAGE_FAULT_ERROR_CODE_MASK);
    VMX_DUMP(PAGE_FAULT_ERROR_CODE_MATCH);
    VMX_DUMP(CR3_TARGET_COUNT);
    VMX_DUMP(VM_EXIT_CONTROLS);
    VMX_DUMP(VM_EXIT_MSR_STORE_COUNT);
    VMX_DUMP(VM_EXIT_MSR_LOAD_COUNT);
    VMX_DUMP(VM_ENTRY_CONTROLS);
    VMX_DUMP(VM_ENTRY_MSR_LOAD_COUNT);
    VMX_DUMP(VM_ENTRY_INTR_INFO_FIELD);
    VMX_DUMP(VM_ENTRY_EXCEPTION_ERROR_CODE);
    VMX_DUMP(VM_ENTRY_INSTRUCTION_LEN);
    VMX_DUMP(TPR_THRESHOLD);
    VMX_DUMP(SECONDARY_VM_EXEC_CONTROL);
    VMX_DUMP(PLE_GAP);
    VMX_DUMP(PLE_WINDOW);
    VMX_DUMP(VM_INSTRUCTION_ERROR);
    VMX_DUMP(VM_EXIT_REASON);
    VMX_DUMP(VM_EXIT_INTR_INFO);
    VMX_DUMP(VM_EXIT_INTR_ERROR_CODE);
    VMX_DUMP(IDT_VECTORING_INFO_FIELD);
    VMX_DUMP(IDT_VECTORING_ERROR_CODE);
    VMX_DUMP(VM_EXIT_INSTRUCTION_LEN);
    VMX_DUMP(VMX_INSTRUCTION_INFO);
    VMX_DUMP(GUEST_ES_LIMIT);
    VMX_DUMP(GUEST_CS_LIMIT);
    VMX_DUMP(GUEST_SS_LIMIT);
    VMX_DUMP(GUEST_DS_LIMIT);
    VMX_DUMP(GUEST_FS_LIMIT);
    VMX_DUMP(GUEST_GS_LIMIT);
    VMX_DUMP(GUEST_LDTR_LIMIT);
    VMX_DUMP(GUEST_TR_LIMIT);
    VMX_DUMP(GUEST_GDTR_LIMIT);
    VMX_DUMP(GUEST_IDTR_LIMIT);
    VMX_DUMP(GUEST_ES_AR_BYTES);
    VMX_DUMP(GUEST_CS_AR_BYTES);
    VMX_DUMP(GUEST_SS_AR_BYTES);
    VMX_DUMP(GUEST_DS_AR_BYTES);
    VMX_DUMP(GUEST_FS_AR_BYTES);
    VMX_DUMP(GUEST_GS_AR_BYTES);
    VMX_DUMP(GUEST_LDTR_AR_BYTES);
    VMX_DUMP(GUEST_TR_AR_BYTES);
    VMX_DUMP(GUEST_INTERRUPTIBILITY_INFO);
    VMX_DUMP(GUEST_ACTIVITY_STATE);
    VMX_DUMP(GUEST_SYSENTER_CS);
    VMX_DUMP(VMX_PREEMPTION_TIMER_VALUE);
    VMX_DUMP(HOST_IA32_SYSENTER_CS);
    VMX_DUMP(CR0_GUEST_HOST_MASK);
    VMX_DUMP(CR4_GUEST_HOST_MASK);
    VMX_DUMP(CR0_READ_SHADOW);
    VMX_DUMP(CR4_READ_SHADOW);
    VMX_DUMP(CR3_TARGET_VALUE0);
    VMX_DUMP(CR3_TARGET_VALUE1);
    VMX_DUMP(CR3_TARGET_VALUE2);
    VMX_DUMP(CR3_TARGET_VALUE3);
    VMX_DUMP(EXIT_QUALIFICATION);
    VMX_DUMP(GUEST_LINEAR_ADDRESS);
    VMX_DUMP(GUEST_CR0);
    VMX_DUMP(GUEST_CR3);
    VMX_DUMP(GUEST_CR4);
    VMX_DUMP(GUEST_ES_BASE);
    VMX_DUMP(GUEST_CS_BASE);
    VMX_DUMP(GUEST_SS_BASE);
    VMX_DUMP(GUEST_DS_BASE);
    VMX_DUMP(GUEST_FS_BASE);
    VMX_DUMP(GUEST_GS_BASE);
    VMX_DUMP(GUEST_LDTR_BASE);
    VMX_DUMP(GUEST_TR_BASE);
    VMX_DUMP(GUEST_GDTR_BASE);
    VMX_DUMP(GUEST_IDTR_BASE);
    VMX_DUMP(GUEST_DR7);
    VMX_DUMP(GUEST_RSP);
    VMX_DUMP(GUEST_RIP);
    VMX_DUMP(GUEST_RFLAGS);
    VMX_DUMP(GUEST_PENDING_DBG_EXCEPTIONS);
    VMX_DUMP(GUEST_SYSENTER_ESP);
    VMX_DUMP(GUEST_SYSENTER_EIP);
    VMX_DUMP(HOST_CR0);
    VMX_DUMP(HOST_CR3);
    VMX_DUMP(HOST_CR4);
    VMX_DUMP(HOST_FS_BASE);
    VMX_DUMP(HOST_GS_BASE);
    VMX_DUMP(HOST_TR_BASE);
    VMX_DUMP(HOST_GDTR_BASE);
    VMX_DUMP(HOST_IDTR_BASE);
    VMX_DUMP(HOST_IA32_SYSENTER_ESP);
    VMX_DUMP(HOST_IA32_SYSENTER_EIP);
    VMX_DUMP(HOST_RSP);
    VMX_DUMP(HOST_RIP);
    kprintfd("}\n");
}
